global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - "0.0.0.0:9090"
          # - "0.0.0.0:3000"
          # - "0.0.0.0:3333"
